server:
  port: 4050

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: pig
    password: lengleng

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023